name: Prepare Environment
description: Prepare the environment by setting up Node.js and installing dependencies using bun
runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2

    - name: Setup Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      shell: bash
      run: bun ci

    - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      shell: bash
      run: npm audit signatures
