on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-slim
    environment: main
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release-please
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node

    outputs:
      release-created: ${{ steps.release-please.outputs.releases_created }}

  publish-npm:
    needs: release-please
    if: needs.release-please.outputs.release-created == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: bun run build

      - name: Publish to npm
        run: npm publish --access public
