name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: bun run build

      - name: Release
        run: npx semantic-release@25.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
